# Generated by Django 6.0.8 on 2026-08-20 22:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alter_floodalert_geom'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('health_status', models.CharField(choices=[('healthy', 'Healthy'), ('stressed', 'Stressed'), ('critical', 'Critical')], max_length=10)),
                ('confidence_score', models.FloatField()),
                ('reason', models.TextField()),
                ('source', models.CharField(default='Sentinel-2 NDVI', max_length=100)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('validated_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HeatZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('confidence_score', models.FloatField()),
                ('reason', models.TextField()),
                ('source', models.CharField(default='Landsat Thermal', max_length=100)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('validated_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
            ],
        ),
    ]
